---
title: "describe univariate for Kaggle challenge: Tabular Playground Series - Feb 2022"
author: "Sascha Siegmund"
date: "`r Sys.Date()`"
output: 
  github_document:
    fig_width: 10
    fig_height: 7
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "nb_figs/uni_",
  warning = FALSE,
  message = FALSE
)
```



## purpose of notebook

  - [ ] describe & visualize single variables (univariate)
  - [ ] gather interesting observations for further investigation
  - [ ] gather possible new features for extraction
  
  
## insights 

  - 
  

## load packages

```{r load packages, setup, message=FALSE}
library(tidyverse) # tidy data frame
library(plotly) # make ggplots interactive
library(ggmosaic) # for mosaic plots 
library(GGally) # for parallel coordinate plots
library(ggridges) # for ridgeline plots
```


## import data

```{r, message=FALSE}
df <- read_csv('../data/train.csv')
df2 <- read_csv('../data/train_clean.csv')
```


## overview

```{r}
head(df)
```
```{r}
summary(df)
```


## overview with heatmap
- 

```{r fig.height=20, fig.width=10}
tmp_df <- df %>% mutate(target = factor(target)) %>% 
  group_by(target) %>% mutate(row_id = row_number()) %>% ungroup() %>%
  pivot_longer(!c('row_id', 'target'))  

p1 <- tmp_df %>% 
  ggplot(aes(x = name, y = row_id, fill = value)) +
    geom_tile(show.legend = FALSE) +
    scale_fill_viridis_c() +
    facet_grid(rows = vars(target)) +
    theme_minimal() 

p1
```

```{r fig.height=20, fig.width=10}
tmp_df <- df2 %>% mutate(target = factor(target)) %>% 
  group_by(target) %>% mutate(row_id = row_number()) %>% ungroup() %>%
  pivot_longer(!c('row_id', 'target'))  

p1 <- tmp_df %>% 
  ggplot(aes(x = name, y = row_id, fill = value)) +
    geom_tile(show.legend = FALSE) +
    scale_fill_viridis_c() +
    facet_grid(rows = vars(target)) +
    theme_minimal() 

p1
```

```{r fig.height=20, fig.width=10}
set.seed(3)
tmp_df <- df2 %>% mutate(target = factor(target)) %>% sample_frac(0.0001) %>% 
  group_by(target) %>% mutate(row_id = row_number()) %>% ungroup() %>% 
  pivot_longer(!c('row_id', 'target'))

p1 <- tmp_df %>% 
  ggplot(aes(x = name, y = row_id, fill = value)) +
    geom_tile(show.legend = FALSE) +
    scale_fill_viridis_c() +
    facet_grid(rows = vars(target)) +
    theme_minimal() 

ggplotly(p1)
```


## explore numerical univariate variable

- 

```{r}
# one variable, continuous x, show distribution
name = 'A3T4G3C0'
tmp_df <- df %>% rename(value = name) %>% select(value) %>% add_count(value) %>% 
  mutate(fn = factor(n))

p1 <- tmp_df %>%
  ggplot(aes(x = value)) +
    stat_density(geom = 'line', position = 'identity') +
    theme_minimal()  
p1 <- ggplotly(p1) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p2 <- tmp_df %>%
  ggplot(aes(x = value)) +
    geom_spoke(aes(y = -n, radius = 2*n, angle = pi/2, text = paste0("value: ", value, "\ncount: ", n)),
               alpha = 0.5, stat = "unique") +  # y = 0, radius = n for one-sided spoke plot
    ggtitle(paste("distribution of", name, sep=" ")) +
    theme_minimal() 
p2 <- ggplotly(p2, tooltip = 'text') %>% layout()

p3 <- tmp_df %>%
  ggplot(aes(x = 1, y = value)) +
    geom_boxplot() +
    theme_minimal() +
    coord_flip() 
p3 <- ggplotly(p3) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p5 <- tmp_df %>%
  ggplot() +
    geom_mosaic(aes(x=product(fn))) +
    theme_minimal() +
    coord_flip()
p5 <- ggplotly(p5) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

# https://plotly.com/r/subplots/
fig <- subplot(p2, p5,
               p1, plotly_empty(),
               p3, plotly_empty(), 
               nrows = 3, margin = 0, heights = c(0.8, 0.1, 0.1), 
               widths = c(0.95, 0.05), shareX = TRUE) %>% 
  layout(xaxis = list(title = name))

fig
```

```{r}
# one variable, continuous x, show distribution
name = 'A3T5G0C2'
tmp_df <- df %>% rename(value = name) %>% select(value) %>% add_count(value) %>% 
  mutate(fn = factor(n))

p1 <- tmp_df %>%
  ggplot(aes(x = value)) +
    stat_density(geom = 'line', position = 'identity') +
    theme_minimal()  
p1 <- ggplotly(p1) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p2 <- tmp_df %>%
  ggplot(aes(x = value)) +
    geom_spoke(aes(y = -n, radius = 2*n, angle = pi/2, text = paste0("value: ", value, "\ncount: ", n)),
               alpha = 0.5, stat = "unique") +  # y = 0, radius = n for one-sided spoke plot
    ggtitle(paste("distribution of", name, sep=" ")) +
    theme_minimal() 
p2 <- ggplotly(p2, tooltip = 'text') %>% layout()

p3 <- tmp_df %>%
  ggplot(aes(x = 1, y = value)) +
    geom_boxplot() +
    theme_minimal() +
    coord_flip() 
p3 <- ggplotly(p3) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p5 <- tmp_df %>%
  ggplot() +
    geom_mosaic(aes(x=product(fn))) +
    theme_minimal() +
    coord_flip()
p5 <- ggplotly(p5) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

# https://plotly.com/r/subplots/
fig <- subplot(p2, p5,
               p1, plotly_empty(),
               p3, plotly_empty(), 
               nrows = 3, margin = 0, heights = c(0.8, 0.1, 0.1), 
               widths = c(0.95, 0.05), shareX = TRUE) %>% 
  layout(xaxis = list(title = name))

fig
```

```{r}
# one variable, continuous x, show distribution
name = 'A0T1G2C7'
tmp_df <- df %>% rename(value = name) %>% select(value) %>% add_count(value) %>% 
  mutate(fn = factor(n))

p1 <- tmp_df %>%
  ggplot(aes(x = value)) +
    stat_density(geom = 'line', position = 'identity') +
    theme_minimal()  
p1 <- ggplotly(p1) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p2 <- tmp_df %>%
  ggplot(aes(x = value)) +
    geom_spoke(aes(y = -n, radius = 2*n, angle = pi/2, text = paste0("value: ", value, "\ncount: ", n)),
               alpha = 0.5, stat = "unique") +  # y = 0, radius = n for one-sided spoke plot
    ggtitle(paste("distribution of", name, sep=" ")) +
    theme_minimal() 
p2 <- ggplotly(p2, tooltip = 'text') %>% layout()

p3 <- tmp_df %>%
  ggplot(aes(x = 1, y = value)) +
    geom_boxplot() +
    theme_minimal() +
    coord_flip() 
p3 <- ggplotly(p3) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p5 <- tmp_df %>%
  ggplot() +
    geom_mosaic(aes(x=product(fn))) +
    theme_minimal() +
    coord_flip()
p5 <- ggplotly(p5) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

# https://plotly.com/r/subplots/
fig <- subplot(p2, p5,
               p1, plotly_empty(),
               p3, plotly_empty(), 
               nrows = 3, margin = 0, heights = c(0.8, 0.1, 0.1), 
               widths = c(0.95, 0.05), shareX = TRUE) %>% 
  layout(xaxis = list(title = name))

fig
```


## explore categorical univariate variable

- 

```{r}
# one variable, categorical x, show distribution
name = 'target'
tmp_df <- df %>% rename(value = name) %>% select(value) %>% 
  mutate(value = fct_infreq(factor(value))) %>% 
  add_count(value) %>% mutate(percent = n / nrow(.))

p1 <- tmp_df %>%
  ggplot(aes(x = value)) +
    geom_bar() +
    geom_text(aes(label = paste0(n, "\n", scales::percent(percent,  accuracy = 0.1)),
                  y = max(tmp_df$n)*0.94), stat = "unique", size = 3.5) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle=45, vjust=0.7, size=10))
p1 <- ggplotly(p1) %>% layout()

p2 <- tmp_df %>%
  ggplot(aes(x = 1, y = value)) +
    geom_boxplot(fill = 'lightgrey') +
    theme_minimal() +
    coord_flip() +
    ggtitle(paste("distribution of", name, sep=" ")) +
    theme(axis.text.x = element_text(angle=45, vjust=0.7, size=10))
p2 <- ggplotly(p2) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE))

p5 <- tmp_df %>%
  ggplot() +
    geom_mosaic(aes(x=product(value))) +
    theme_minimal() +
    coord_flip()
p5 <- ggplotly(p5) %>% layout(yaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''), 
                              xaxis = list(showticklabels = FALSE, showgrid = FALSE, title = ''))

# https://plotly.com/r/subplots/
fig <- subplot(p1, p5, p2, plotly_empty(), nrows = 2, margin = 0, 
               heights = c(0.9, 0.1), widths = c(0.95, 0.05), shareX = TRUE) %>% 
  layout(xaxis = list(title = name))

fig
```








